version: "3.8"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py_docker
    ports:
      - "8080:80"  # Adjust the port mapping as needed
    # Other configurations or volumes can be added here if required