name: Deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: my-arithmetic-$USER deployment on stable servers
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install poetry-dynamic-versioning
        pip3 install tox
        poetry install
        poetry build
        ls dist/
